export const theme = {
    colors: {
        text: {
            primary: '#172234',
            secondary: '#A2A0A2',
            tertiary: '#808080',
        },
        balanceSlider: '#36343B',
        surface: {
            primary: '#f2f2f2',
            secondary: '#141414',
            tertiary: '#161616',
            quaternary: '#1C1C1C',
            quinary: '#1C1C1E',
            tag: '#282828',
        },
        border: {
            neutral: '#393939',
            neutralDark: '#434343',
            active: '#D1D7E0',
        },
        accentColor: {
            default: '#D83253',
            error: '#DC1A1A',
            purple: '#8148F9',
            teal: '#1C8F9A',
            orange: '#D28228',
            red: '#E23230',
            green: '#0C8C72',
            blue: '#5350EE',
            pink: '#C94EB5',
            yellow: '#FCB005',
            lightBlue: '#1D7ED7',
            lightGreen: '#1D7ED7',
        },
        categories: {
            work: '#ED6524',
            learn: '#9E8FF4',
            life: '#D2DC43',
        },
    },
    fontSizes: {
        xs: '8px',
        s: '12px',
        m: '14px',
        l: '16px',
        xl: '24px',
        '2xl': '28px',
        '3xl': '36px',
    },
    fontWeights: {
        medium: 500,
        light: 300,
        thin: 100,
    },
    borders: {
        none: 'none',
        normal: '1px solid',
        bold: '2px solid',
    },
    borderRadius: {
        small: '4px',
        mediumSmall: '8px',
        medium: '10px',
        mediumLarge: '16px',
        large: '12px',
        extraLarge: '20px',
        superLarge: '32px',
        round: '50%',
    },
};